### ISSUE TITLE
Floating type variables won't work in GHC 9.2

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-compat/deriving-compat#34]
If you try to compile the `deriving-compat` test suite with a recent enough GHC HEAD (which will eventually become 9.2), you'll end up running into this error:

```
[ 2 of 14] Compiling DerivingViaSpec  ( tests/DerivingViaSpec.hs, /home/ryanglscott/Documents/Hacking/Haskell/deriving-compat-0.5.10/dist-newstyle/build/x86_64-linux/ghc-9.1.20210322/deriving-compat-0.5.10/t/spec/build/spec/spec-tmp/DerivingViaSpec.o, /home/ryanglscott/Documents/Hacking/Haskell/deriving-compat-0.5.10/dist-newstyle/build/x86_64-linux/ghc-9.1.20210322/deriving-compat-0.5.10/t/spec/build/spec/spec-tmp/DerivingViaSpec.dyn_o )
tests/DerivingViaSpec.hs:45:2-49: Splicing declarations
    deriveGND [t| forall a. Eq a => Eq (Down a) |]
  ======>
    instance forall a. Eq a => Eq (Down a) where
      (==) :: Down a -> Down a -> Bool
      (/=) :: Down a -> Down a -> Bool
      (==)
        = (ghc-prim:GHC.Prim.coerce
             @(a -> a -> Bool) @(Down a -> Down a -> Bool))
            (==)
      (/=)
        = (ghc-prim:GHC.Prim.coerce
             @(a -> a -> Bool) @(Down a -> Down a -> Bool))
            (/=)

<elided>

tests/DerivingViaSpec.hs:45:2: error:
    Instance head cannot contain nested ‘forall’s or contexts
    In an instance declaration
   |
45 | $(deriveGND [t| forall a. Eq a => Eq (Down a) |])
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Although `-ddump-splices` prints out `instance forall a. Eq a => Eq (Down a) where`, this is somewhat of a lie. It's really more like `instance (forall a. Eq a => Eq (Down a)) where`, as `deriving-compat` uses a nested `ForallT` to give the illusion that the instance begins with a top-level `forall`. While this worked on previous versions of GHC, GHC 9.2 now calls us on our bluff.

Barring a change to `template-haskell`, I don't see a way to make this work under GHC 9.2. We may just have to remove the nested `ForallT` trick altogether. This will break some programs that were made to compile in #27, but oh well.

**Comment by RyanGlScott** [comment]
Upon further thought, there actually _is_ a way to continue supporting floating `via` type variables, even without nested `ForallT`s. See a82cbf7.
